# Site settings
title: TheBanditDave
name: David Hamilton
brand: TheBanditDave
email: thebanditdave@gmail.com
description: TheBanditDave's website and blog.
url: "http://thebanditdave.com" # the base hostname & protocol for your site
twitter: TheBanditDave
github: TheBanditDave
analytics: 
year: 2016

# Build settings
markdown: kramdown
permalink: /:title
exclude :
  - node_modules

#Default settings
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      author: David Hamilton
      layout: "post"
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages" # previously `post` in Jekyll 2.2.
    values:
      layout: "page"
